
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'datavaultdemo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'datavaultdemo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  datavaultdemo:
    staging:
      materialized: incremental
      tags: ["staging"]
    hubs:
      materialized: incremental
      tags: ["hubs"]
      

# Seeds configuration
seeds:
  datavaultdemo:
    customers:
      +column_types:
        customer_id:  int
        first_name:   varchar(25)
        last_name:    varchar(25)
        email:        varchar(25)
        phone:        varchar(25)
        join_date:    date
    orders:
      +column_types:
        order_id:     int
        customer_id:  int
        product_id:   int
        order_date:   date
        order_amount: decimal(10,2)